[2022-04-06 17:51:32,123] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail manual__2022-04-06T17:51:30.876617+00:00 [queued]>
[2022-04-06 17:51:32,135] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail manual__2022-04-06T17:51:30.876617+00:00 [queued]>
[2022-04-06 17:51:32,135] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:51:32,136] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 17:51:32,136] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:51:32,149] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): sendmail> on 2022-04-06 17:51:30.876617+00:00
[2022-04-06 17:51:32,154] {standard_task_runner.py:52} INFO - Started process 1825 to run task
[2022-04-06 17:51:32,156] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_mail', 'sendmail', 'manual__2022-04-06T17:51:30.876617+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmp9pzrlk75', '--error-file', '/tmp/tmpgsoat0qv']
[2022-04-06 17:51:32,157] {standard_task_runner.py:80} INFO - Job 19: Subtask sendmail
[2022-04-06 17:51:32,223] {logging_mixin.py:109} INFO - Running <TaskInstance: send_mail.sendmail manual__2022-04-06T17:51:30.876617+00:00 [running]> on host 669712b97f52
[2022-04-06 17:51:32,287] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_mail
AIRFLOW_CTX_TASK_ID=sendmail
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T17:51:30.876617+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-06T17:51:30.876617+00:00
[2022-04-06 17:51:34,211] {logging_mixin.py:109} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials u62-20020a638541000000b00382791c89efsm16894269pgd.13 - gsmtp')
[2022-04-06 17:51:34,211] {python.py:175} INFO - Done. Returned value was: None
[2022-04-06 17:51:34,226] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=send_mail, task_id=sendmail, execution_date=20220406T175130, start_date=20220406T175132, end_date=20220406T175134
[2022-04-06 17:51:34,254] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 17:51:34,289] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
